name: DEPLOY
on:
  pull_request:
    branches:
    - master
    paths:
    - "ede.js"
  push:
    branches:
    - master
    paths:
    - "ede.js"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Pack
      run: |
        rm -rf public
        mkdir -p public
        cp ede.js public/ede.user.js
    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
    - name: Purge CDN cache
      run: |
        curl https://purge.jsdelivr.net/gh/RyoLee/dd-danmaku/ede.js
        curl https://purge.jsdelivr.net/gh/RyoLee/dd-danmaku@gh-pages/ede.user.js